In [1]:
import pandas as pd
import numpy as np

In [2]:
true = pd.read_csv('True.csv')

In [3]:
fake = pd.read_csv('Fake.csv')

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
true['label']=1

In [7]:
fake['label'] = 0

In [8]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [9]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [10]:
news = pd.concat([fake,true],axis=0)

In [11]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [13]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [14]:
news = news.drop(['title','subject','date'],axis=1)

In [15]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [16]:
news = news.sample(frac=1)

In [17]:
news.head()

                                                    text  label
15267  BRUSSELS (Reuters) - U.S. Defense Secretary Ji...      1
15714  BRUSSELS (Reuters) - Belgian authorities have ...      1
20367  After 9 Months Of Hard-Core Islam Muslim  Cloc...      0
21134  It turns out we re not as divided as people ma...      0
10696  MSNBC host Thomas Roberts on Sunday was specul...      0

In [18]:
news.reset_index(inplace=True)

In [19]:
news.head()

   index                                               text  label
0  15267  BRUSSELS (Reuters) - U.S. Defense Secretary Ji...      1
1  15714  BRUSSELS (Reuters) - Belgian authorities have ...      1
2  20367  After 9 Months Of Hard-Core Islam Muslim  Cloc...      0
3  21134  It turns out we re not as divided as people ma...      0
4  10696  MSNBC host Thomas Roberts on Sunday was specul...      0

In [20]:
news.drop(['index'],axis=1, inplace = True)

In [21]:
news.head()

                                                text  label
0  BRUSSELS (Reuters) - U.S. Defense Secretary Ji...      1
1  BRUSSELS (Reuters) - Belgian authorities have ...      1
2  After 9 Months Of Hard-Core Islam Muslim  Cloc...      0
3  It turns out we re not as divided as people ma...      0
4  MSNBC host Thomas Roberts on Sunday was specul...      0

In [22]:
import re

In [23]:
def wordopt(text):
    text = text.lower()

    text = re.sub(r'https?://\S+|www\.\S+','',text)

    text = re.sub(r'[^\w\s]','',text)

    text = re.sub(r'\d','',text)

    text = re.sub(r'\n','',text)

    return text

In [24]:
news['text'] = news['text'].apply(wordopt)

In [25]:
news['text']

0        brussels reuters  us defense secretary jim mat...
1        brussels reuters  belgian authorities have rec...
2        after  months of hardcore islam muslim  clock ...
3        it turns out we re not as divided as people ma...
4        msnbc host thomas roberts on sunday was specul...
                               ...
44893    following the horrific tragedy in dallas texas...
44894    tokyo reuters  japan s coast guard on thursday...
44895    washington reuters  the us senate intelligence...
44896    bill clinton has been accused of multiple rape...
44897    washington reuters  the united states has made...
Name: text, Length: 44898, dtype: object

In [26]:
x = news['text']
y = news['label']

In [27]:
x

0        brussels reuters  us defense secretary jim mat...
1        brussels reuters  belgian authorities have rec...
2        after  months of hardcore islam muslim  clock ...
3        it turns out we re not as divided as people ma...
4        msnbc host thomas roberts on sunday was specul...
                               ...
44893    following the horrific tragedy in dallas texas...
44894    tokyo reuters  japan s coast guard on thursday...
44895    washington reuters  the us senate intelligence...
44896    bill clinton has been accused of multiple rape...
44897    washington reuters  the united states has made...
Name: text, Length: 44898, dtype: object

In [28]:
y

0        1
1        1
2        0
3        0
4        0
        ..
44893    0
44894    1
44895    1
44896    0
44897    1
Name: label, Length: 44898, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [31]:
x_train.shape

(31428,)

In [32]:
x_test.shape

(13470,)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vectorization = TfidfVectorizer()

In [35]:
xv_train = vectorization.fit_transform(x_train)

In [36]:
xv_test = vectorization.transform(x_test)

In [37]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6472706 stored elements and shape (31428, 175041)>

In [38]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2708829 stored elements and shape (13470, 175041)>

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
LR = LogisticRegression()

In [41]:
LR.fit(xv_train, y_train)

LogisticRegression()

In [42]:
pred_lr = LR.predict(xv_test)

In [43]:
LR.score(xv_test, y_test)

0.9881217520415738

In [44]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [45]:
print(classification_report(y_test, pred_lr))
print("Accuracy:", accuracy_score(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7096
           1       0.98      0.99      0.99      6374

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

Accuracy: 0.9881217520415738
[[6992  104]
 [  56 6318]]

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
DTC = DecisionTreeClassifier()

In [48]:
DTC.fit(xv_train, y_train)

DecisionTreeClassifier()

In [49]:
pred_dtc = DTC.predict(xv_test)

In [50]:
DTC.score(xv_test, y_test)

0.9962138084632517

In [51]:
print(classification_report(y_test, pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7096
           1       1.00      1.00      1.00      6374

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
rfc = RandomForestClassifier()

In [54]:
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [55]:
predict_rfc = rfc.predict(xv_test)

In [56]:
rfc.score(xv_test, y_test)

0.9862657757980697

In [57]:
print(classification_report(y_test, predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7096
           1       0.98      0.99      0.99      6374

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [58]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
gbc = GradientBoostingClassifier()

In [60]:
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [61]:
pred_gbc = gbc.predict(xv_test)

In [62]:
gbc.score(xv_test, y_test)

0.9953229398663697

In [63]:
print(classification_report(y_test, pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7096
           1       0.99      1.00      1.00      6374

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

## Quick Start:

In [7]:
import re
import joblib
import pandas as pd

# Same text-cleaning function used during training
def wordopt(text):
    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d', '', text)
    text = re.sub(r'\n', '', text)
    return text

def output_label(n):
    if n == 0:
        return "It is a Fake News"
    elif n == 1:
        return "It is a Genuine News"

# Load the saved vectorizer and models from disk
vectorization = joblib.load('vectorizer.jb')
LR = joblib.load('model_lr.jb')
DTC = joblib.load('model_dtc.jb')
gbc = joblib.load('model_gbc.jb')
rfc = joblib.load('model_rfc.jb')

print("Loaded saved vectorizer and models. Ready to predict.")

Loaded saved vectorizer and models. Ready to predict.

In [8]:
def manual_testing(news):
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)

    # Apply the same cleaning used during training
    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    # Transform using the SAME vectorizer used for training
    new_xv_test = vectorization.transform(new_def_test["text"])

    pred_lr = LR.predict(new_xv_test)
    pred_dt = DTC.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)

    return (
        "\n\nLR Prediction: {}"
        "\nDT Prediction: {}"
        "\nGBC Prediction: {}"
        "\nRFC Prediction: {}"
    ).format(
        output_label(pred_lr[0]),
        output_label(pred_dt[0]),
        output_label(pred_gbc[0]),
        output_label(pred_rfc[0])
    )

In [13]:
news_article = str(input())

 President Donald Trump announced yesterday that he plans to formally recognize Jerusalem as the capital of Israel. While this is left most pundits perplexed, the reasoning is clear. Trump wants to divert attention from Robert Mueller s investigation. It is no coincidence that the day after the news broke that Deutsche Bank has received subpoenas for information on the Trump family s assets, that this Jerusalem decision was announced. What could be a bigger news story than getting this information? A blow up in the Middle East.Look at the reaction world leaders have had to this announcement. American allies throughout the Middle East and Europe have asked Trump not to do this and have stressed how dangerous a statement this is. US News and World Report put this out today: The mere consideration of Trump changing the status quo sparked a renewed U.S. security warning on Tuesday. America s consulate in Jerusalem ordered U.S. personnel and their families to avoid visiting Jerusalem s Old City or the West Bank, and urged American citizens in general to avoid places with increased police or military presence. It is worth noting that while Trump will formally announce that the U.S. will recognize Jerusalem as Israel s capital, there is no movement underway to relocate the embassy from Tel Aviv. In fact, he has signed an order to delay that decision for another six months. This move is necessary due to the 1995 Jerusalem Embassy Act, which mandated the embassy be moved. It also allowed the president to delay that by six months and every president since that act became law has done so this way.The Atlantic has even compared this decision to Trump  wagging the dog,  a reference to a movie where a U.S. president goes to war with Albania to take the public s attention away from his own scandals involving a mistress. The film was viewed as a parody of President Bill Clinton s military actions in Afghanistan and Sudan after he acknowledged an affair with Monica Lewinsky.While whether or not Clinton attacked other countries to distract the nation from his actions with Lewinsky may be a point that is up for debate, it is clear that Trump likes to do things to distract the public s attention. Catherine Rampell wrote about this tactic late last year in the Washington Post. She wrote: Welcome to 2017, the ouroboros of distractions, where every terrible thing is a head-fake for a ruse for a diversion for a misdirection from something else much, much worse. Trump makes announcements, sends tweets and says things without any thought to the real world consequences that follow. Experts in the Middle East fear that the Jerusalem announcement will lead to real deaths. Many people worry  that his thoughtless and impetuous tweets will lead to a nuclear war. His thoughtless comments confuse and enrage many.By making such a move, for such purely personal reasons, Trump is proving, once again, that he is not fit to be president of a condo association, much less of the United States.Featured image by Andrew Burton/Getty Images.

In [14]:
print(manual_testing(news_article))

LR Prediction: It is a Fake News
DT Prediction: It is a Fake News
GBC Prediction: It is a Fake News
RFC Prediction: It is a Fake News